local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>df', builtin.find_files, {desc="[d]irectory: Fuzzy [f]ind Files"})
vim.keymap.set('n', '<leader>dS', function()
	builtin.grep_string({ search = vim.fn.input("Grep > ") })
end, {desc="[d]irectory: List files including [S]tring"})
vim.keymap.set('n', '<leader>gf', builtin.git_files, {desc="[g]it: Fuzzy Find Git [f]iles"})
